/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CompDefault: typeof import('./src/components/CompDefault.vue')['default']
    CompDialog: typeof import('./src/components/CompDialog.vue')['default']
    CompFooter: typeof import('./src/components/CompFooter.vue')['default']
    CompHeader: typeof import('./src/components/CompHeader.vue')['default']
    CompLoading: typeof import('./src/components/CompLoading.vue')['default']
    CompPopup: typeof import('./src/components/CompPopup.vue')['default']
    CompSkeleton: typeof import('./src/components/CompSkeleton.vue')['default']
    CompSortIcon: typeof import('./src/components/CompSortIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
